Fix #2, add react-native-web dependency and update App.js
shadaj/expo-template-scala pull request #7
Opened 2020-10-03 01:04 UTC by manuzhang

As per [solutions](https://github.com/shadaj/expo-template-scala/issues/2#issuecomment-669303248) provided by @thesamet

2020-10-03 04:05 UTC, manuzhang commented
@shadaj, I've only tested with local project created from this template so I'm not sure it works for new project. Please let me know if there is a way to test it.

2020-10-03 18:01 UTC, shadaj requested changes
Just one nit, but otherwise LGTM! We don't have much of a testing process for this template, checking with a local project has been the way I test as well so we should be good to go ahead with the changes.

2020-10-03 18:01 UTC, shadaj commented on package.json
> +		"react-native-web": "^0.13.14",
The indentation seems off here

2020-10-04 23:33 UTC, manuzhang commented
Thanks. Indent fixed.

2020-10-04 23:57 UTC, shadaj approved these changes

2020-10-04 23:57 UTC, merged